In [ ]:
!pip install -q kagglehub

In [ ]:
import kagglehub
import pandas as pd
import numpy as np
import os

In [ ]:
path = kagglehub.dataset_download("anuchhetry/electronic-health-record")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/anuchhetry/electronic-health-record/1.archive...

100%|██████████| 75.5k/75.5k [00:00<00:00, 40.7MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/anuchhetry/electronic-health-record/versions/1

In [ ]:
print("Files in dataset folder:")

for file in os.listdir(path):
    print(file)

Files in dataset folder:
EHR.csv

In [ ]:
csv_files = [file for file in os.listdir(path) if file.endswith('.csv')]

print("CSV files found:")
print(csv_files)

CSV files found:
['EHR.csv']

In [ ]:
file_path = os.path.join(path, csv_files[0])

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [ ]:
df.head()

,patientunitstayid,patienthealthsystemstayid,gender,age,ethnicity,hospitalid,wardid,apacheadmissiondx,admissionheight,hospitaladmittime24,...,unitadmitsource,unitvisitnumber,unitstaytype,admissionweight,dischargeweight,unitdischargetime24,unitdischargeoffset,unitdischargelocation,unitdischargestatus,uniquepid
0,210014,182373,Male,45,Caucasian,73,89,"Hypertension, uncontrolled (for cerebrovascula...",178.0,13:08:59,...,Direct Admit,1,admit,116.0,112.7,15:00:00,4424,Skilled Nursing Facility,Alive,002-10665
1,200026,174624,Male,50,Caucasian,71,87,Ablation or mapping of cardiac conduction pathway,177.8,10:41:00,...,Operating Room,1,admit,106.1,106.1,17:40:00,1548,Home,Alive,002-10715
2,221131,190993,Male,83,Caucasian,71,87,"Endarterectomy, carotid",175.3,21:43:00,...,Operating Room,1,admit,NaN,72.1,17:46:00,1203,Home,Alive,002-10249
3,221215,191054,Male,49,Caucasian,71,87,"Infarction, acute myocardial (MI)",185.4,03:16:00,...,Emergency Department,1,admit,145.3,146.6,19:07:00,1562,Home,Alive,002-10627
4,217835,188445,Male,57,Caucasian,73,92,"CABG alone, coronary artery bypass grafting",172.7,01:09:00,...,Operating Room,1,admit,NaN,80.4,08:25:00,4719,Floor,Alive,002-10324

In [ ]:
df.tail()

,patientunitstayid,patienthealthsystemstayid,gender,age,ethnicity,hospitalid,wardid,apacheadmissiondx,admissionheight,hospitaladmittime24,...,unitadmitsource,unitvisitnumber,unitstaytype,admissionweight,dischargeweight,unitdischargetime24,unitdischargeoffset,unitdischargelocation,unitdischargestatus,uniquepid
1442,1107527,823049,Male,77,Caucasian,199,487,NaN,172.7,18:35:00,...,ICU to SDU,2,stepdown/other,70.3,NaN,17:51:00,4576,Rehabilitation,Alive,010-10461
1443,1107528,823049,Male,77,Caucasian,199,487,"Pneumonia, other",172.7,18:35:00,...,Step-Down Unit (SDU),1,admit,75.3,NaN,13:35:00,4651,Step-Down Unit (SDU),Alive,010-10461
1444,1112115,826318,Female,78,Caucasian,199,490,"Sepsis, GI",162.6,21:33:00,...,Step-Down Unit (SDU),1,admit,110.4,NaN,12:40:00,4090,Floor,Alive,010-10636
1445,1099377,817241,Male,78,Caucasian,199,491,"Pneumonia, bacterial",195.6,05:10:00,...,Step-Down Unit (SDU),1,stepdown/other,108.0,NaN,13:25:00,10063,Floor,Alive,010-10171
1446,1098722,816777,Female,78,Caucasian,199,495,"Respiratory - medical, other",162.6,05:54:00,...,Step-Down Unit (SDU),1,admit,63.5,NaN,19:44:00,12969,Home,Alive,010-10099

In [ ]:
print("Number of records:", df.shape[0])
print("Number of features:", df.shape[1])

Number of records: 1447
Number of features: 29

In [ ]:
print("Features in the EHR dataset:\n")

for i, column in enumerate(df.columns, 1):
    print(i, "→", column)

Features in the EHR dataset:

1 → patientunitstayid
2 → patienthealthsystemstayid
3 → gender
4 → age
5 → ethnicity
6 → hospitalid
7 → wardid
8 → apacheadmissiondx
9 → admissionheight
10 → hospitaladmittime24
11 → hospitaladmitoffset
12 → hospitaladmitsource
13 → hospitaldischargeyear
14 → hospitaldischargetime24
15 → hospitaldischargeoffset
16 → hospitaldischargelocation
17 → hospitaldischargestatus
18 → unittype
19 → unitadmittime24
20 → unitadmitsource
21 → unitvisitnumber
22 → unitstaytype
23 → admissionweight
24 → dischargeweight
25 → unitdischargetime24
26 → unitdischargeoffset
27 → unitdischargelocation
28 → unitdischargestatus
29 → uniquepid

In [ ]:
print(df.dtypes)

patientunitstayid              int64
patienthealthsystemstayid      int64
gender                        object
age                           object
ethnicity                     object
hospitalid                     int64
wardid                         int64
apacheadmissiondx             object
admissionheight              float64
hospitaladmittime24           object
hospitaladmitoffset            int64
hospitaladmitsource           object
hospitaldischargeyear          int64
hospitaldischargetime24       object
hospitaldischargeoffset        int64
hospitaldischargelocation     object
hospitaldischargestatus       object
unittype                      object
unitadmittime24               object
unitadmitsource               object
unitvisitnumber                int64
unitstaytype                  object
admissionweight              float64
dischargeweight              float64
unitdischargetime24           object
unitdischargeoffset            int64
unitdischargelocation         object
unitdischargestatus           object
uniquepid                     object
dtype: object